### ISSUE TITLE
Disable presence when paused/idle options

### ISSUE THREAD

**Issue by Reinbowsaur** [tnychn/mpv-discord#11]
Could be different too something like, if paused for (custom timer) then disable presence until state play state changes. Setting timer to 0, would instantly disable presense on pause.

If you were able to implement this feature, I'd be downloading changing to using your version of RPC in a heartbeat. I don't know why so many people like sharing useless details that they are paused or left their player open. 

Cheers, hope you consider this feature.

**Comment by tnychn** [comment]
I implemented your suggestion but I don't think allowing users to instantly disable the presense on pause by setting a `0` threshold is a good idea. If the user pauses the player frequently, it might potentially break the program as there would be too many dis/reconnections. I don't think the client could handle it.

The current implementation is that the presence will only hide when paused if the `autohide_threshold`  option in the config is `> 0` to prevent users from specifying a `0` threshold.

**Comment by Reinbowsaur** [comment]
One week of use, absolutely no problems. Loved the response time for this additon! I did have some trouble with the using the installer script (windows 10) (it did nothing, open and closed, i might have being inputting my location wrong) and ended up moving files to appropiate places manually.

**Comment by tnychn** [comment]
Thanks! I will check out the Windows installer script again.
