### ISSUE TITLE
Not showing up in Discord for me

### ISSUE THREAD

**Issue by Masteroduo** [tnychn/mpv-discord#12]
I tried doing what was instructed but for some reason it still doesn't show up in discord for some reason. Here are the screenshots of where I copied all the files.
![image](https://user-images.githubusercontent.com/79645349/112457132-83135a00-8d6c-11eb-91c1-4a7244b1f45d.png)
![image](https://user-images.githubusercontent.com/79645349/112457299-adfdae00-8d6c-11eb-8260-9c2901649e6e.png)

Here is how discord.conf is configured
![image](https://user-images.githubusercontent.com/79645349/112457438-d38ab780-8d6c-11eb-8abb-de1f671778bd.png)

Even though mpv is playing a video file it doesn't show up in discord.
![image](https://user-images.githubusercontent.com/79645349/112457663-0634b000-8d6d-11eb-8582-2efbda145b6a.png)

I'm pretty sure this might be something done wrong on my part since almost everyone has gotten it working properly however due to being a complete noob to Discord RPC's and stuff like that,I don't know the reason for why it doesn't show up for me. 

Thanks :)

**Comment by tnychn** [comment]
Try changing the `binary_path` option to `C:\Program Files (x86)\mpv\mpv-discord`.
