### ISSUE TITLE
Installed this and tried to make it work with iina but iina doesn't open now

### ISSUE THREAD

**Issue by SleepyRabbitXVI** [tnychn/mpv-discord#14]
So i ran the script in terminal as I saw your comment somewhere that this can be used with iina for discord rich presence but after following all the steps and changing the directory in iina's preferences > advance to config/mpv I quit iina and tried opening it but now it won't open at all. I moved the mpv-discord file to trash and tried reinstalling iina as well but still the same issue. In short I can't open iina now no matter what so I'd appreciate it if you can help me with this.

**Comment by SleepyRabbitXVI** [comment]
Okay so I ran `defaults delete com.colliderli.iina` in terminal which restores the default settings of iina and it opens now. Still no idea why this happened, if you know the reason and could help me set this up for rich presence using iina I'd appreciate it a lot.

**Comment by tnychn** [comment]
I guess your mpv-discord config was wrong, particularly the `binary_path` option. If this option points to a non-existing path, IINA will not open.

**Comment by SleepyRabbitXVI** [comment]
Okay i ran `install_darwin.sh` again and i get this 

`Copying config [discord.conf]
Copying script [discord.lua]
Copying prebuilt darwin binary [mpv-discord]
Done! Please manually edit the following option in the config file:
binary_path=/Users/aryanshetty/.config/mpv/discord
Path to mpv directory: /Users/aryanshetty/.config/mpv
Path to config file: /Users/aryanshetty/.config/mpv/script-opts/discord.conf`

Edited the `discord.conf` file to this

`key=D
active=yes
binary_path=/Users/aryanshetty/.config/mpv/discord
socket_path=/tmp/mpvsocket
use_static_socket_path=yes
autohide_threshold=0`

i did the exact same thing last time and in iina i did this preferences > advanced > use config directory: /Users/aryanshetty/.config/mpv

quit iina and it won't open

do i need to have mpv installed or maybe do some other stuff in addition to this? 
I'm sorry for bothering you.

**Comment by tnychn** [comment]
You don't need to have mpv installed.
Check if the `binary_path` does exist and is pointing to the mpv-discord binary.
Make sure IINA has write access to `/tmp`. If it requires root permissions, you may specify another `socket_path`.
