### ISSUE TITLE
[REQUEST] Add IINA icon for use with IINA

### ISSUE THREAD

**Issue by NoaHimesaka1873** [tnychn/mpv-discord#15]
It would be nice to have IINA icon option for IINA users. It works great with IINA!

**Comment by tnychn** [comment]
Released `v1.6.0` with the custom client ID option implemented. You can now set the `client_id` option in the config to `834116350884577280` to use it with IINA. Image assets used can be found [here](https://github.com/tnychn/mpv-discord/tree/v1.6.0/assets/834116350884577280).

**Comment by NoaHimesaka1873** [comment]
Great! Thank you!
