### ISSUE TITLE
New version not showing presence in discord

### ISSUE THREAD

**Issue by Metokel** [tnychn/mpv-discord#16]
![image](https://user-images.githubusercontent.com/59681368/115563619-53635d80-a2ea-11eb-84a8-2bc8c05047a4.png)
![image](https://user-images.githubusercontent.com/59681368/115563753-72fa8600-a2ea-11eb-9c51-33477af0853d.png)
So I tested the new version and it does not appear on my discord. Previous version worked before.

**Comment by tnychn** [comment]
`v1.6.0` introduces a new required option (`client_id`) in the config. Please check if you have set a valid value to it.

**Comment by Metokel** [comment]
There is a default value I didn't change it. Should I make a new app in the portal?

**Comment by tnychn** [comment]
It should work fine with the default client ID. It may be a bug. Could you provide your config (`discord.conf`) for debugging?

**Comment by Metokel** [comment]
Here is my config file in zip since I can't upload .conf files
[config.zip](https://github.com/tnychn/mpv-discord/files/6355570/config.zip)

**Comment by tnychn** [comment]
Your `binary_path` option is wrong. It should be the path to mpv-discord's binary file.

**Comment by Metokel** [comment]
I actually have the mpv-discord.exe in that directory. I tried transferring the bin folder to my mpv , changed the binary and it still didn't work. Can I see a sample to follow? That would help me thank you.
