### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Wanted135** [tnychn/mpv-discord#17]
Hello, kinda stuck and don't understand the inscructions at all, please help. ty.

**Comment by tnychn** [comment]
Which part do you not understand, the installation or configuration or ...?

**Comment by Wanted135** [comment]
The installation, I am stuck at the binary path. I opened the bath file and
typed in the patch to mpv

**Comment by zaafuro** [comment]
maybe your path contains spaces, in which case you would need to put quotation marks around it

**Comment by Wanted135** [comment]
It does not contain any space, I just don't know what's the binary_path and how I can make it work

**Comment by tnychn** [comment]
The `binary_path` should be the path to mpv-discord's binary (the one inside the zip you downloaded from [releases](https://github.com/tnychn/mpv-discord/releases)), not mpv's binary.

**Comment by Wanted135** [comment]
![explorer_9JM6vwz8iQ](https://user-images.githubusercontent.com/34011489/116353316-8adb7980-a7c4-11eb-9cb5-f6ba88c1e7f3.png)
![notepad++_ImAll04Srb](https://user-images.githubusercontent.com/34011489/116353366-a0e93a00-a7c4-11eb-9d49-f0fae68a39f1.png)
Is this ok?

**Comment by tnychn** [comment]
This is just the folder path. You need to point it to the binary file itself, which is `C:\Users\name\Downloads\mpv rich\bin\windows\mpv-discord.exe`.

**Comment by Wanted135** [comment]
Okay, ty I will try

**Comment by Wanted135** [comment]
> This is just the folder path. You need to point it to the binary file itself, which is `C:\Users\name\Downloads\mpv rich\bin\windows\mpv-discord.exe`.

I feel like it doesnt work, do I have to do extra steps ?

**Comment by tnychn** [comment]
Try using a path without whitespace. And where did you place the `discord.lua`, `discord.conf` files respectively?

**Comment by Wanted135** [comment]
![image](https://user-images.githubusercontent.com/34011489/116362711-5968ab00-a7d0-11eb-910c-f6c6d51da4e3.png)
I will try, and I placed them here

**Comment by Wanted135** [comment]
![image](https://user-images.githubusercontent.com/34011489/116362840-8026e180-a7d0-11eb-9d16-943ec2a44d52.png)
This have to be filled or not ?

**Comment by Wanted135** [comment]
Okay, it worked you can close this now, thank you for your help.
