### ISSUE TITLE
Could not get it working in Linux: dial unix /tmp/mpvsocket: connect: connection refused

### ISSUE THREAD

**Issue by spitfire-hash** [tnychn/mpv-discord#19]
Hi there

I could not get it working in my Linux machine. I did everything according to instructions, but it doesn't seem to work. The log is like:

```
[discord] mpv-discord v1.6.0 by tnychn
[discord] (mpv-ipc): /tmp/mpvsocket
[discord] launched subprocess
[discord] dial unix /tmp/mpvsocket: connect: connection refused
.....
[discord] aborted subprocess
```
The problem probably occurs when connection is refused. I couldn't find when you log this, but I thikn this is from mpv-discord module(the backend).
My configurations and stuff is all fine. Please tell me if you need any other information.

**Comment by tnychn** [comment]
The socket file wasn't created properly, that's why the connection is refused.

Try setting another socket path where you have read/write permissions in config (e.g. `socket_path=/path/to/mpvsocket`). If it still doesn't work, try setting `use_static_socket_path=no` in config.

**Comment by spitfire-hash** [comment]
I have read/write permissions in /tmp. Altough, I changed it to `~/.local/share/mpv/socket`, It still says connection refused.

Changing `use_static_socket_path` to `no`, resulted(i just changed `socket_path` too)
```
dial unix /home/murad/.cache/mpv/socket/mpv-discord-2998: connect: no such file or directory
```
