### ISSUE TITLE
Possible to change 'Playing A Game'

### ISSUE THREAD

**Issue by theoneandonly-1** [tnychn/mpv-discord#20]
Activity type Enum is a parameter in Discord that can display what the rich presence is playing .e.g Streaming, Playing etc
https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum

Is it possible to set that in the config file?

**Comment by theoneandonly-1** [comment]
<img width="246" alt="Screenshot 2021-05-25 at 14 46 41" src="https://user-images.githubusercontent.com/72360538/119508868-0864bc00-bd68-11eb-843c-0d16e1003d1c.png">
This is what it shows when playing a Soundcloud stream

**Comment by RythenGlyth** [comment]
I don't think this will work, the [docs you linked](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum) say

> ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, it will be discarded and will not change anything in the client.

**Comment by tnychn** [comment]
I don't think this is possible. Only the `Playing` type can be customized with status text. Other types are for other particular usages.
