### ISSUE TITLE
need help in installation

### ISSUE THREAD

**Issue by TheHeroicFrog1** [tnychn/mpv-discord#22]
I don't know anything about scripts and things like this so I am having trouble installation like I don't any steps of installation please help.

**Comment by yuisempai** [comment]
> I don't know anything about scripts and things like this so I am having trouble installation like I don't any steps of installation please help.

Here's a quick way to install in windows in case `install_windows.bat` not working:

step 1: Extract the .zip and copy `scripts` and `scripts-opts` folders and `mpv-discord.exe` to mpv directory.

step 2: Edit `scripts-opts\discord.conf` and write path to `mpv-discord.exe` i.e. `<your mpv directory>\mpv-discord.exe` next to `binary_path=` . 
           For example: `binary_path=C:\Program Files\mpv\mpv-discord.exe`

**Comment by TheHeroicFrog1** [comment]
by  directory you means this folder right ?
![Screenshot (49)](https://user-images.githubusercontent.com/85406980/120918151-844bf600-c6d0-11eb-813f-4486cfbd29e1.png)
and i have to paste scripts and scripts-opts folders here or the contents of these folders in the folder already present here named scripts and scripts-opts.

**Comment by TheHeroicFrog1** [comment]
well i don't know how but now whenever i open mpv it shows discord rich presence started in top left corner but it doesn't update my discord status

**Comment by yuisempai** [comment]
yeah paste scripts and scripts-opts (or its contents if folder already present) there and in discord.conf you need to specify full path to mpv-discord.exe like `C:\Program Files\mpv\mpv-discord.exe`

**Comment by yuisempai** [comment]
mpv-discord.exe does not necessarily need to be in this directory, just paste the 

> well i don't know how but now whenever i open mpv it shows discord rich presence started in top left corner but it doesn't update my discord status

that's because you haven't specified the path to `mpv-discord.exe` correctly

**Comment by TheHeroicFrog1** [comment]
Well I did I pasted it at C:\Program Files\mpv\mpv where the scripts and scrit-opts folder is and I specified this path in the discord.config file

**Comment by yuisempai** [comment]
your mpv folder should look like this
![Screenshot 2021-06-06 144610](https://user-images.githubusercontent.com/85407503/120919299-71d4bb00-c6d6-11eb-98fd-1d90bb3c9194.png)

and your discord.conf should look like this
![Screenshot 2021-06-06 144822](https://user-images.githubusercontent.com/85407503/120919319-916be380-c6d6-11eb-8821-7dd874f23a11.png)

**Comment by tnychn** [comment]
Example directory structure:
```
C:\Program Files\mpv
├── d3dcompiler_43.dll
├── doc
│   └── (...)
├── installer
│   └── (...)
├── mpv
│   └── (...)
├── mpv-discord.exe 👈🏻
├── mpv-install.bat
├── mpv-uninstall.bat
├── mpv.com
├── mpv.exe
├── script-opts
│   └── discord.conf 👈🏻
├── scripts
│   └── discord.lua 👈🏻
└── updater.bat

(Files pointed by a finger belong to mpv-discord. Others belong to mpv itself.)
If the folders `scripts` and `script-opts` do not exist yet, create them.
```
In the above setup, the `binary_path` would be `C:\Program Files\mpv\mpv-discord.exe`.

**Comment by yuisempai** [comment]
yeah that is absolutely correct, is it working now?

**Comment by yuisempai** [comment]
@tnychn i'm sorry for the comment right now i thought it was @TheHeroicFrog1 





(will be deleted after few minutes)

**Comment by TheHeroicFrog1** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/85406980/120921607-23c5b480-c6e2-11eb-9a1f-e3a982728dd9.png)
![Screenshot (51)](https://user-images.githubusercontent.com/85406980/120921610-26280e80-c6e2-11eb-9ddc-9d1fbebf3bae.png)
correct?

now when i open install_windows.bat it asks for a path so i have paste this C:\Program Files\mpv\mpv-discord.exe or just enter 
in both cases it shows some kind of text then closes and it too fast to be able to read

**Comment by yuisempai** [comment]
You don't need to run `install_windows.bat` now, you are done already. Just open discord and play something on mpv and see if it's working.

**Comment by TheHeroicFrog1** [comment]
Thank you it's working now
