### ISSUE TITLE
Lua error: /home/skilledhasbadpc/.config/mpv/scripts/discord.lua:20: attempt to call field 'file_info' (a nil value)

### ISSUE THREAD

**Issue by SkilledHasBadPC** [tnychn/mpv-discord#23]
![Screenshot 2021-06-22 20:31:24](https://user-images.githubusercontent.com/36399055/122933897-3f46e580-d399-11eb-8f8b-74e50ae7241f.png)

**Comment by tnychn** [comment]
Fixed at 8fb3216. You can test it out just by replacing `discord.lua` with the [updated version](https://github.com/tnychn/mpv-discord/blob/8fb3216430/scripts/discord.lua).
