### ISSUE TITLE
Lua error: /home/ezra/.config/mpv/scripts/discord.lua:53: attempt to call field 'command_native_async' (a nil value)

### ISSUE THREAD

**Issue by reacto11mecha** [tnychn/mpv-discord#27]
I downloaded release v1.6.0 and tried to installed it and this error message appear

My System: MX Linux 19 Patito Feo
mpv version: 0.29.1

![image](https://user-images.githubusercontent.com/48118327/130209852-e96d9516-4b3a-4fec-afa2-ba89b376c22c.png)

**Comment by tnychn** [comment]
Upgrade your mpv to the latest version (or at least `>= v0.30.0`).
