### ISSUE TITLE
Binary_path

### ISSUE THREAD

**Issue by neemanthnub** [tnychn/mpv-discord#33]
Can you explain more about the binary_path?

**Comment by tnychn** [comment]
The file path to the mpv-discord binary. You can find it [here](https://github.com/tnychn/mpv-discord/tree/master/bin).

If you run the installer script (which comes with the zip that you have downloaded from [releases](https://github.com/tnychn/mpv-discord/releases)), it will place the binary in the right location and show you the binary path. You don't have to figure it out on your own.

This is the example output of the installer script for Darwin:
```
Path to mpv directory: /Users/neemanthnub/.config/mpv
Path to config file: /Users/neemanthnub/.config/mpv/script-opts/discord.conf

You're almost done!
Please manually edit the following option in the config file:

  binary_path=/Users/neemanthnub/.config/mpv/discord
```

Note that `binary_path` does not mean the path to the discord app executable. The binary it refers to is is the compiled Go program of this project for handling message interchange between discord and mpv.

**Comment by tnychn** [comment]
Related issues #12, #22, in case anyone needs help on installing and configuring mpv-discord.
