### ISSUE TITLE
Can't open mpv after installing mpv-discord

### ISSUE THREAD

**Issue by simdesu** [tnychn/mpv-discord#41]
I followed the manual and installed mpv-discord, however now I can't open mpv.exe (it just does not do anything after I open it) unless I remove 'discord.lua' from the 'scripts' folder. Any way to fix this?

**Comment by Njezi** [comment]
You have to go to your mpv path then script-opts and open discord.conf

You have to edit this line to discord.exe in your mpv
for example: binary_path=C:\mpv\discord.exe

**Comment by simdesu** [comment]
Seems like I was adding the binary_path line to the discord.conf file located in the mpv-discord/script-opts folder, not the actual mpv/script-opts one. Fixed it and it works flawlessly now. Thank you!
