### ISSUE TITLE
Windows installer script does not work as intended

### ISSUE THREAD

**Issue by Viniuau** [tnychn/mpv-discord#5]
I tried installing it on mpv.net, even manually copying and editing the config files, but without success.

Did I miss something? Or does the script not work with mpv.net?

**Comment by tnychn** [comment]
I made the plugin for the original mpv player but haven't test it on other mpv based players. But in theory, it should work fine on them as long as they are using the same user-scripting mechanism with mpv. Maybe you put the files in the wrong location? Or you can try using it with mpv and see if it works. If it still doesn't work then the plugin probably has bugs on Windows that need to be fixed.

**Comment by Viniuau** [comment]
Apparently, the script copys the folder, but fails to copy its contents like the discord.lua file. This time I am using the original mpv binary compiled from sourceforge.

https://user-images.githubusercontent.com/19510529/107222257-72449a00-69f3-11eb-9248-47a3f3a770d5.mp4

**Comment by tnychn** [comment]
Oh I see. I will fix this in the coming release. For now, as a workaround you can manually put `discord.lua` inside `scripts`, `discord.conf` inside `script-opts` and put `discord.exe` next to `mpv.exe`.

**Comment by Viniuau** [comment]
![image](https://user-images.githubusercontent.com/19510529/107241608-e8ec9200-6a09-11eb-99d7-daa8590c5bf8.png)
It works fine with MPV, but it doesn't work with MPV.NET
![image](https://user-images.githubusercontent.com/19510529/107241924-3832c280-6a0a-11eb-91b3-80745f08c6fe.png)

I'm thinking this is a unique behavior to mpv.net. You can close this issue if you don't intend to make it work with mpv.net, I won't bother you with that.

**Comment by tnychn** [comment]
I think making it work with mpv is enough. But I will keep this issue for now as this is also related to the problems of the Windows installer script.
