### ISSUE TITLE
Not displaying info (OS X)

### ISSUE THREAD

**Issue by toooonyy** [tnychn/mpv-discord#6]
Using macOS 10.14, mpv build with luajit

```[discord] Opened config file script-opts/discord.conf.
[discord] (mpv-ipc): /tmp/mpvsocket/mpv-discord-67018
[cplayer] Set property: input-ipc-server="/tmp/mpvsocket/mpv-discord-67018" -> 1
[discord] mpv-discord v1.3.1 by tnychn
[ipc] Starting IPC master
[ipc] Could not bind IPC socket
```

~~Is this a script or mpv's problem?~~

---------
You need to run `xattr -d com.apple.quarantine discord` first otherwise Apple block the binary from runing, but now how can I display the info in discord(I'm think the script is running properly rn?)
```
[discord] Opened config file script-opts/discord.conf.
[discord] (mpv-ipc): /tmp/mpvsocket
[cplayer] Set property: input-ipc-server="/tmp/mpvsocket" -> 1
[discord] mpv-discord v1.3.1 by tnychn
[ipc] Starting IPC master
[ipc] Listening to IPC socket.
```

**Comment by tnychn** [comment]
If you already have `active=yes` set in the config, then now it should work (rich presence shows up in Discord) when you are playing something in mpv. See if the messages `[discord] (discord-ipc): connected` and `[discord] (mpv-ipc): connected` are printed to console.

**Comment by toooonyy** [comment]
Ah, I can see 
```
[discord] Opened config file script-opts/discord.conf.
[discord] (mpv-ipc): /tmp/mpvsocket
[discord] mpv-discord v1.3.1 by tnychn
[discord] launched subprocess
```
but not other logs, so it's still no working?

**Comment by toooonyy** [comment]
Now if I run  `./discord /tmp/mpvsocket` manually after opening mpv everything works fine.

**Comment by tnychn** [comment]
Since you said the binary works fine when you launch it manually, the problem should be related to mpv and its LuaJIT instead. Note that the prebuilt Darwin binary you found on [releases](https://github.com/tnychn/mpv-discord/releases) is for AMD64 Mac. Though I don't think it can work on ARM Mac.

**Comment by toooonyy** [comment]
Ok, then it's a arm problme.
