### ISSUE TITLE
Add PKGBIUILD and get on the AUR.

### ISSUE THREAD

**Issue by TheOPtimal** [tnychn/mpv-discord#9]
We could adapt the `install_linux.sh` script into a PKGBUILD and publish it on the AUR (not a hard process).

For those who don't know, the AUR stands for Arch User Repository and is an unofficial repository for Arch users to install things not in the official repositories.

**Comment by tnychn** [comment]
I don't plan to publish it on the AUR yet.

**Comment by satcom886** [comment]
@tnychn Packaging this should be pretty simple, I'll do it if you want to.
